baseurl = "http://www.pzhao.org"
# relativeurls = true
title = "Peng Zhao"
copyright = "&copy; 2017 Peng Zhao"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

# Enable comments by entering your Disqus shortname
disqusShortname = "pzhao"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[blackfriday]
  hrefTargetBlank = true

[params]
  name = "Peng Zhao"
  role = "Post-doc in Geoecology"
  organization = "University of Innsbruck"
  organization_url = ""
  avatar = "zhao.jpg"
  email = "peng.zhao@uibk.ac.at"
  address = "Sternwartestr. 15, Innsbruck Austria"
  office_hours = "Monday 10:00 to 13:00 or email for appointment"
  phone = "+43 (0)512 507-51643"
  skype = ""
  RSS = "http://www.pzhao.org/zh/index.xml"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = []
  # highlight_style = "github"
  # highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:peng.zhao@uibk.ac.at"

  [[params.social]]
    icon = "youtube"
    icon_pack = "fa"
    link = "https://www.youtube.com/channel/UCs76tyulNUTPSzagsuTA8UA"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.at/citations?user=EFeUfDwAAAAJ&hl=zh-CN"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/dapengde"

  [[params.social]]
    icon = "rss"
    icon_pack = "fa"
    link = "http://www.pzhao.org/zh/index.xml"

  [[params.social]]
    icon = "music"
    icon_pack = "fa"
    link = "http://kg.qq.com/node/personal?uid=649d9d85212c3489"

  [[params.social]]
    icon = "video-camera"
    icon_pack = "fa"
    link = "http://v.qq.com/vplus/0f8190586a3f2f22a25e9827b38c171e"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[menu.main]]
  name = "中文"
  url = "../zh"
  weight = 7

[[languages.zh.menu.main]]
  name = "主页"
  url = "#about"
  weight = 1

[[languages.zh.menu.main]]
  name = "论文"
  url = "#publications"
  weight = 3

[[languages.zh.menu.main]]
  name = "最新"
  url = "#posts"
  weight = 2

[[languages.zh.menu.main]]
  name = "项目"
  url = "#projects"
  weight = 4

[[languages.zh.menu.main]]
  name = "教学"
  url = "#teaching"
  weight = 5

[[languages.zh.menu.main]]
  name = "联系"
  url = "#contact"
  weight = 6

[[languages.zh.menu.main]]
  name = "搜索"
  url = "https://cse.google.com/cse/publicurl?cx=006346710622437628329:nxozn9fijm0"
  weight = 8

[[languages.zh.menu.main]]
  name = "EN"
  url = "../en"
  weight = 7

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

[languages.zh]
  languageCode = "zh-cn"
